        <footer id="footer" class="clearfix">
            
			<div id="contact">
				<h4>Contact</h4>
				<h6><a href="mailto:alex@digitalfrontiersman.com"target=_blank> alex@digitalfrontiersman.com </a></h6>
	            <ul class="clearfix">
					<li> </li>
	                <li><a href="http://instagram.com/alexbloom"target=_blank> <span aria-hidden="true" class="icon-instagram" title=" Bikes, signs, and American finds. - Instagram"> </span> </br> Instagram  </a></li>
					<li><a href="http://vimeo.com/alexbloom"target=_blank> <span aria-hidden="true" class="icon-vimeo" title="Videos, mostly travel. - Vimeo"> </span> </br> Vimeo </a></li>
					
					<li><a href="http://twitter.com/alexbloom"target=_blank> <span aria-hidden="true" class="icon-twitter" title="Haikus, conversations, and links. - Twitter"> </span> </br> Twitter </a></li>
					
					<!-- <li><a href="http://tumblr.com/alexbloom"target=_blank> <span aria-hidden="true" class="icon-tumblr" title="Haikus, conversations, and links. - Twitter"> </span></br> Tumblr </a></li> -->
					
					<li> </li>
	            </ul>
			
			</div>

			<div id="newsletter">
				<!-- Begin MailChimp Signup Form -->
				
				<form action="http://alexbloom.us4.list-manage.com/subscribe/post?u=c1a7163cb6a015c28453eddea&amp;id=13093c8f7e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
					<h4>Newsletter</h4>
					<input type="text" placeholder="Email Address" name="cm-yhujlld-yhujlld" id="yhujlld-yhujlld">
				    <input type="submit" id="submit" alt="Sign Up" value="Sign Up">
				
				</form>
				
				<small> A succinct, monthly offering of ideas and entertainment for the benefit of mankind, never to include solicitation, self-promotion, bullshit, or <a href=""target=_blank>canned meat.</a> Your information will never be shared. 
				</small>
				<!--End mc_embed_signup-->
			</div>

			<hr>
			<div id="copyright">
            <small> &ldquo;Take the physical challenge.&rdquo; All Content © Alex Bloom 2010&ndash;2013 </small>
			</div>
			
			
        </footer>

        <!-- Scripts -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
	
        <script>
            var _gaq=[['_setAccount','UA-45493428-1'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>	
    </body>
</html>