<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title> Digital Frontiersman </title>
		<meta name="author" content="Alex Bloom">
        <meta name="description" content="The Traveling Office of Alex Bloom.">
		<meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="viewport" content="width = device-width, initial-scale=1, maximum-scale=1, user-scalable = no">
		<meta name="keywords" content="Interaction Design, User Experience, Web Development, Alex Bloom, America">
		
		
		
		<link rel="canonical" href="http://www.sandbox.tribecafilminstitute.org/tfi-new-media-fund/2014" />
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="article" />
		<meta property="og:title" content="TFI New Media Fund - 2014 Funded Projects - TFI Sandbox" />
		<meta property="og:description" content="The TFI New Media Fund is a grant for filmmakers pushing the boundaries of traditional filmmaking and documentary work." />
		<meta property="og:url" content="http://www.sandbox.tribecafilminstitute.org/tfi-new-media-fund/2014" />
		<meta property="og:site_name" content="TFI Sanxbox" />
		<meta property="article:published_time" content="2014-02-04T21:43:55+00:00" />
		<meta property="article:modified_time" content="2014-02-07T19:41:37+00:00" />
		<meta property="og:image" content="http://www.sandbox.tribecafilminstitute.org/tfi-new-media-fund/2014/" />
		

		<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="css/base.css">
		<link rel="stylesheet" href="css/custom.css">

       <!-- <script src="js/vendor/modernizr-2.6.2.min.js"></script>-->
		<script type="text/javascript" src="//use.typekit.net/ssu8inj.js"></script>
		<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
		
    </head>
    <body>

        <header id="header" class="clearfix">
        	
			<nav id="primary" class="clearfix">
	        	<div id="email-btn">
					<a class="" href="#"><span aria-hidden="true" class="icon-mail" title="Email">  </span> </a>
				</div>
				
				<ul class="clearfix">
					<li><a href="#"> Personal </a></li>
					<li><a href="#"> Professional </a></li>
					<li><a href="#"> Societal </a></li>
				</ul>
				
	        	<div id="search-btn">
					<a class="" href="#"><span aria-hidden="true" class="icon-search" title="Search"> </span> </a> 
				</div>
			</nav>
        	
			
			<div id="search-wrap" class="clearfix">
				<form role="search" method="get" class="search-form" action="">
					<label class="clearfix">
						<span class="screen-reader-text">Search for:</span>
					</label>
					<input type="search" class="search-field" placeholder="Search …" value="" name="s" title="Search for:" />

					<input type="submit" class="search-submit" value="Search" />
				</form>
			</div>	
        </header>
